version: 2.1

orbs:
  macos: circleci/macos@2.1.0 

jobs:
  disk:
    parameters:
      xcode-version:
        type: string
    macos:
      xcode: << parameters.xcode-version >>
    steps:
      - run:
          name: check disk
          command: |
            df -H

workflows:
  big-mac:
    jobs:
      - disk:
          matrix:
            parameters:
              xcode-version:
                - 13.2.0
                - 12.4.0

