version: 2.1

orbs:
  macos: circleci/macos@2.1.0 

jobs:
  showcase-shell:
    macos:
      xcode: 13.4.1
    steps:
      - run: |
          pwd
      - run: |
          cd /usr/local/src
      - run: |
          pwd
      - run: |
          export FOO=bar
          printenv FOO
      - run: |
          printenv FOO || true

workflows:
  big-mac:
    jobs:
      - showcase-shell
