version: 2.1

orbs:
  macos: circleci/macos@2.1.0 

jobs:
  bat-mac:
    macos:
      xcode: 13.2.1
    steps:
      - checkout
      - macos/add-uitest-permissions
      - macos/add-safari-permissions
      - macos/add-permission:
          bundle-id: "com.apple.Terminal"
          permission-type: "kTCCServiceScreenCapture"
      - macos/add-permission:
          bundle-id: "com.apple.Terminal"
          permission-type: "kTCCServiceAccessibility"
      - macos/list-permissions
      - run:
          name: Setting Screen Resolution
          command:
              /Library/Application\ Support/VMware\ Tools/vmware-resolutionSet 1280 768
      - run:
          name: Add VNC user
          command: |
              sudo /usr/sbin/sysadminctl -addUser vncuser -fullName "VNC User" -password Automation@1234 -admin
              sleep 2
              sudo cp -r /Users/distiller/project/.circleci /Users/vncuser/

      - run:
          name: Installing Robot Framework (Mac)
          command: |
              echo "Mac Machine is up"
              pip3 install robotframework
              pip3 install robotframework-seleniumlibrary
              pip3 install robotframework-pabot
              pip3 install robotframework-SikuliLibrary
              mkdir test_results



      - run:
          name: BAT Tests
          command: |
              echo "Starting BAT Tests"
              robot -d test_results/ -i Mac -d robot/results/mac/ robot/temp_test/test.robot
      - run: |
          ls -laH
      - store_test_results:
          path: robot/results

      - store_artifacts:
          path: robot/results

workflows:
  big-mac:
    jobs:
      - bat-mac
